name: Build Docker image

on:
  workflow_call:
    inputs:
      context:
        description: "Context for the Docker build"
        type: string
        required: true
      image-name:
        description: "Name of the Docker image"
        type: string
        required: true
      retention-days:
        description: "Number of days to retain the docker image"
        type: number
        default: 1
      build-args:
        description: "Build arguments"
        type: string
        required: false

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          tags: ${{ inputs.image-name }}:${{ github.sha }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ inputs.image-name }}-docker-image.tar
          cache-from: type=gha,scope=${{ inputs.image-name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}
          build-args: ${{ inputs.build-args }}
          
      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image-name }}-docker-image
          path: ${{ runner.temp }}/${{ inputs.image-name }}-docker-image.tar
          retention-days: ${{ inputs.retention-days }}
